//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesRelax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIES_INFO
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string DirectorsCode { get; set; }
        public string ActorsCode { get; set; }
        public string GenresCode { get; set; }
        public string SubtitlesCode { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> ReleaseTime { get; set; }
        public Nullable<int> MovieTime { get; set; }
        public Nullable<decimal> IMDbScrore { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeUpdated { get; set; }
    }
}
