//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesRelax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIE_LIKES
    {
        public string Code { get; set; }
        public string MovieCode { get; set; }
        public string Username { get; set; }
        public Nullable<int> LikeNum { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeUpdated { get; set; }
    }
}
